# Generated by Django 5.2.1 on 2025-06-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('description', models.TextField()),
                ('date_posted', models.DateField()),
                ('remote', models.BooleanField(default=False)),
                ('source', models.CharField(max_length=100)),
                ('priority_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
