# Generated by Django 5.2.1 on 2025-06-07 04:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='url',
            new_name='redirect_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='date_posted',
        ),
        migrations.RemoveField(
            model_name='job',
            name='priority_score',
        ),
        migrations.RemoveField(
            model_name='job',
            name='remote',
        ),
        migrations.RemoveField(
            model_name='job',
            name='source',
        ),
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='salary_max',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='salary_min',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
